name: Grunt Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.12.0
      uses: actions/setup-node@v1
      with:
        node-version: 13.12.0
    - run: npm install
    - run: grunt build
